### ISSUE TITLE
add publiccode.yml

### ISSUE THREAD

**Issue by Smart-City-Muenster** [bCyberGmbH/leezenflow-code#1]
To make this project automatically more visible, we need a `publiccode.yml` file.
Here are [the docs about publiccode.yml](https://publiccodeyml.readthedocs.io/en/latest/) (and [the repo](https://github.com/publiccodeyml/publiccode.yml)) and here is [an online tool to generate this file](https://publiccode-editor.developers.italia.it/).

@bCyberBasti Let me know, if you are able to create a first version of this file or if I should create a pull request.

**Comment by basti481** [comment]
closed by v2.0.0 release
